server:
  port: 8002

spring.datasource.url: jdbc:mysql://sh-cynosdbmysql-grp-ky91abiy.sql.tencentcdb.com:25742
spring.datasource.username: root
spring.datasource.password: Rotoc.111
spring.datasource.driverClassName: com.mysql.jdbc.Driver

mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.touale.cula.entity


#eureka:
#  client:
#    service-url:
#      default-zone: http://127.0.0.1:7001/eureka/
#  instance:
#    instance-id: springcloud-NewsService-8001
#    prefer-ip-address: true