server:
  port: 84



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: web-83
    prefer-ip-address: true

spring:
  application:
    name: web-83

##如果按照一般web工程将页面放在src/main/webapp/WEB-INF/jsp/，则配置前缀
#spring.mvc.view.prefix: /WEB-INF/
#spring.mvc.view.suffix: .jsp
## 配置Tomcat编码
#server.tomcat.uri-encoding: UTF-8
#server.servlet.context-path: /boot
