server:
  port: 81

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: web-81
    prefer-ip-address: true

spring:
  application:
    name: web-81

