server:
  port: 83



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: newsService-83
    prefer-ip-address: true

spring:
  application:
    name: newsService-83